### ISSUE TITLE
자료 이용

### ISSUE THREAD

**Issue by a11ydoer** [mulder21c/seminar#1]
안녕하세요. 이전에 한번 뵈었지요?
다름이 아니라 제가 이번 한국 정보문화 진흥원 교육에 지선생님 자료, [접근가능한 모달](https://mulder21c.github.io/modal-dialog/#%EB%8D%94-%EC%A0%91%EA%B7%BC-%EA%B0%80%EB%8A%A5%ED%95%9C-modal-window) 를 참고해 볼 예제 중 하나로 포함 해서 교육생들에게 링크를 알려줄 생각인데 괜찮으신가 해서 연락드립니다. 예제가 작년 ARIA APG를 참고하고 있기는 하지만 너무 내용이 좋아서요. 혹시 예제로 포함되지 않기를 원하시면 알려주세요.

**Comment by mulder21c** [comment]
@a11ydoer 앗! 안녕하세요~ 박사님~
해당 자료는 작년 접근성 오픈 아카데미에서 사용했던 자료로 늘 오픈되어 있으니 괜찮습니다~ 
저야 널리 알려주시면 오히려 감사합니다 ^^
